accounts/urls.py
# coding=utf-8

from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^update-user/$', views.update_user, name='update_user'),
    url(r'^change-password/$', views.update_password, name='update_password'),
]

logsource/urls.py
# coding=utf-8

from django.conf.urls import url

from . import views



urlpatterns = [
    url(r'^$', views.logsource_list, name='logsource_list'),
]

logsourceassis/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.views.static import serve as serve_static
from django.contrib.auth.views import login, logout

from core import views

admin.site.site_title = 'RCA Admin'
admin.site.site_header = 'RCA'
admin.site.index_title = 'Welcome to RCA'

urlpatterns = [
    url(r'^$', login, {'template_name': 'login.html'}, name='login'),
    url(r'^index/$', views.index, name='index'),
    url(r'^logsources/', include('logsource.urls', namespace='logsource')),
    url(r'^account/', include('accounts.urls', namespace='accounts')),
    url(r'^leave/$', logout, {'next_page': 'index'}, name='logout'),
    url(r'^admin/', admin.site.urls),
]

accounts/models.py
# coding=utf-8

import re

from django.db import models
from django.core import validators
from django.contrib.auth.models import AbstractBaseUser, UserManager, PermissionsMixin


class User(AbstractBaseUser, PermissionsMixin):

    username = models.CharField(
        'Username', max_length=30, unique=True, validators=[
            validators.RegexValidator(
                re.compile('^[\w.@+-]+$'),
                'Please enter a valid name. '
                'It should contain numbers and words '
                'and the characters : @/./+/-/_ .'
                , 'invalid'
            )
        ], help_text='Please specify a short username'
    )
    name = models.CharField('Name', max_length=100, blank=True)
    email = models.EmailField('E-mail', unique=True)
    is_staff = models.BooleanField('Group', default=False)
    is_active = models.BooleanField('Active', default=True)
    date_joined = models.DateTimeField('Created on', auto_now_add=True)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    objects = UserManager()

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'

    def __str__(self):
        return self.name or self.username

    def get_full_name(self):
        return str(self)

    def get_short_name(self):
        return str(self).split(" ")[0]

core/models.py
from django.db import models

# Create your models here.

logsource/models.py
from django.db import models
from accounts.models import User
from django import forms

OPERATOR_CHOICES = (
    ('', '-----------'),
    ('AND', 'AND'),
    ('OR','OR'),
)

class Vendor(models.Model):
    name = models.CharField('Name', max_length=100)
    created = models.DateTimeField('Created', auto_now_add=True)
    modified = models.DateTimeField('Modified', auto_now=True)

    class Meta:
        verbose_name = 'Vendor'
        verbose_name_plural = 'Vendors'
        ordering = ['name']

    def __str__(self):
        return self.name

class Usecase(models.Model):

    logsource = models.ForeignKey('logsource.Logsource', verbose_name='Logsource')
    high = models.CharField('High_level', max_length=100, blank=False)
    number = models.BigIntegerField('UC_#', blank=False)
    type = models.CharField('UC_type', max_length=100, blank=False)
    description = models.TextField('UC description',blank=False, null=True)
    engineer = models.ForeignKey(User, blank=False)
    created = models.DateTimeField('Created', auto_now_add=True)
    modified = models.DateTimeField('Modified', auto_now=True)

    class Meta:
        verbose_name = 'Usecase'
        verbose_name_plural = 'Usecases'
        ordering = ['number']

    def __str__(self):
        return str(self.number)

class Category(models.Model):

    name = models.CharField('Name', max_length=100, blank=False)
    created = models.DateTimeField('Created', auto_now_add=True)
    modified = models.DateTimeField('Modified', auto_now=True)

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'
        ordering = ['name']

    def __str__(self):
        return self.name

class Test(models.Model):
    id = models.BigIntegerField('RTID', unique=True,primary_key=True,blank=False)
    rtparameter = models.CharField('RT_parameters', max_length=100, blank=False)
    description = models.TextField('RT_description', blank=False)
    created = models.DateTimeField('Created', auto_now_add=True)
    modified = models.DateTimeField('Modified', auto_now=True)

    class Meta:
        verbose_name = 'Test'
        verbose_name_plural = 'Tests'
        ordering = ['parameter']

    def __str__(self):
        return str(self.id)


class Rule(models.Model):
    logsource = models.ForeignKey('logsource.Logsource', verbose_name='Logsource')
    name = models.CharField('Rule name', max_length=100, blank=False)
    parameters = models.IntegerField('N_parameters', blank=False)
    created = models.DateTimeField('Created', auto_now_add=True)
    modified = models.DateTimeField('Modified', auto_now=True)

    class Meta:
        verbose_name = 'Rule'
        verbose_name_plural = 'Rules'
        ordering = ['name']

    def __str__(self):
        return self.name


class Qradaridentifier(models.Model):
    id = models.BigIntegerField('QID', unique=True,primary_key=True,blank=False)
    logsource = models.ForeignKey('logsource.Logsource', verbose_name='Logsource')
    name = models.CharField('Qname', max_length=100, blank=False)
    high = models.CharField('High_level', max_length=100, blank=False)
    low = models.CharField('Low_level', max_length=100, blank=False)
    description = models.TextField('Q_description', blank=False)
    created = models.DateTimeField('Created', auto_now_add=True)
    modified = models.DateTimeField('Modified', auto_now=True)

    class Meta:
        verbose_name = 'Qradaridentifier'
        verbose_name_plural = 'Qradaridentifiers'
        ordering = ['name']

    def __str__(self):
        return str(self.id)

class Parameter(models.Model):

    rid = models.ForeignKey('logsource.Rule', verbose_name='RID')
    r_parameter = models.IntegerField('Rule Parameter', blank=False)
    operator = models.CharField('Logic operator', max_length=100, blank=False)
    parameters = models.TextField('Parameter', blank=False)
    rtid = models.ForeignKey('logsource.Test', verbose_name='RTID')
    validation = models.BooleanField(default=True)
    valid_option = models.CharField('Valid Option', max_length=100, blank=True)
    created = models.DateTimeField('Created', auto_now_add=True)
    modified = models.DateTimeField('Modified', auto_now=True)

    class Meta:
        verbose_name = 'Parameter'
        verbose_name_plural = 'Parameters'
        ordering = ['id']

    def __str__(self):
        return str(self.rtid)

class Logsource(models.Model):
    id = models.IntegerField('LSID', unique=True,primary_key=True,blank=False)
    name = models.CharField('LS_Name', max_length=100,blank=False)
    vendor = models.ForeignKey('logsource.Vendor',blank=False, verbose_name='Vendor')
    type = models.CharField('LS_type', max_length=100,blank=False)
    created = models.DateTimeField('Created', auto_now_add=True)
    modified = models.DateTimeField('Modified', auto_now=True)

    class Meta:
        verbose_name = 'Logsource'
        verbose_name_plural = 'Logsources'
        ordering = ['name']

    def __str__(self):
        return self.name


class Cep(models.Model):
    qid = models.ForeignKey('logsource.Qradaridentifier', verbose_name='QID')
    name = models.CharField('Name', max_length=100, blank=False)
    cepnumber = models.IntegerField('Number', blank=False)
    regex = models.TextField('Regex', blank=False)
    created = models.DateTimeField('Created', auto_now_add=True)
    modified = models.DateTimeField('Modified', auto_now=True)

    class Meta:
        verbose_name = 'Cep'
        verbose_name_plural = 'Ceps'
        ordering = ['name']

    def __str__(self):
        return self.name

class Detail(models.Model):
    category = models.ForeignKey('logsource.Category',blank=False, verbose_name='Category')
    ucnum = models.BigIntegerField(blank=False,verbose_name='Use Case Number')
    ucdescription = models.TextField(blank=False, verbose_name='Description')
    logsourcetype = models.TextField(blank=False,verbose_name='Log Type')
    rulename = models.ForeignKey('logsource.Rule', verbose_name='Rule Name')
    operator_one = models.CharField(max_length=3, choices=OPERATOR_CHOICES, blank=True)
    parameter_one = models.TextField('Parameter' ,blank=True)
    test_description_one = models.TextField('RT Description',blank=True)
    regex_one = models.TextField('Regex',blank=True)
    operator_two = models.CharField(max_length=3, choices=OPERATOR_CHOICES, blank=True)
    parameter_two = models.TextField('Parameter',blank=True)
    test_description_two = models.TextField('RT Description',blank=True)
    regex_two = models.TextField('Regex',blank=True)
    operator_three = models.CharField(max_length=3, choices=OPERATOR_CHOICES, blank=True)
    parameter_three = models.TextField('Parameter',blank=True)
    test_description_three = models.TextField('RT Description',blank=True)
    regex_three = models.TextField('Regex',blank=True)
    operator_four = models.CharField(max_length=3, choices=OPERATOR_CHOICES, blank=True)
    parameter_four = models.TextField('Parameter',blank=True)
    test_description_four = models.TextField('RT Description',blank=True)
    regex_four = models.TextField('Regex',blank=True)
    operator_five = models.CharField(max_length=3, choices=OPERATOR_CHOICES, blank=True)
    test_description_five = models.TextField('RT Description',blank=True)
    parameter_five = models.TextField('Parameter',blank=True)
    regex_five = models.TextField('Regex',blank=True)
    operator_six = models.CharField(max_length=3, choices=OPERATOR_CHOICES, blank=True)
    parameter_six = models.TextField('Parameter',blank=True)
    test_description_six = models.TextField('RT Description',blank=True)
    regex_six = models.TextField('Regex',blank=True)
    operator_seven = models.CharField(max_length=3, choices=OPERATOR_CHOICES, blank=True)
    parameter_seven = models.TextField('Parameter',blank=True)
    test_description_seven = models.TextField('RT Description',blank=True)
    regex_seven = models.TextField('Regex',blank=True)
    operator_eight = models.CharField(max_length=3, choices=OPERATOR_CHOICES, blank=True)
    parameter_eight = models.TextField('Parameter',blank=True)
    test_description_eight = models.TextField('RT Description',blank=True)
    regex_eight = models.TextField('Regex',blank=True)
    engineer = models.ForeignKey(User, blank=False)
    created = models.DateTimeField('Created', auto_now_add=True)
    modified = models.DateTimeField('Modified', auto_now=True)

    class Meta:
        verbose_name = 'Detail'
        verbose_name_plural = 'Details'
        ordering = ['id']

    def __str__(self):
        return str(self.id)

core/views.py
# coding=utf-8

from django.shortcuts import render
from django.http import HttpResponse


def index(request):
    return render(request, 'index.html')


def logsource_list(request):
    return render(request, 'logsource_list.html')


def logsource(request):
    return render(request, 'logsource.html')

logsource/views.py
# coding=utf-8

from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse_lazy
from django.views.generic import (
    CreateView, TemplateView, UpdateView, FormView,ListView
)
from django.db import connection
from .models import Logsource,Vendor,Test,Usecase,Category,Rule,Parameter,Qradaridentifier,Cep,Detail


class IndexView(TemplateView):

    template_name = 'logsource/logs.html'



class LogsourceListView(ListView):

    model = Logsource
    template_name = 'logsource/logsource.html'
    context_object_name = 'logs'
    success_url = reverse_lazy('index')

logsource_list = LogsourceListView.as_view()


def logsource_list(request):
    #cursor = connection.cursor()
    #cursor.execute("Select uc.high as category,uc.description as description,ls.type as ltype ,pr.validation as validation, cep.regex as cregex FROM logsource_usecase as uc, logsource_logsource as ls,logsource_parameter as pr, logsource_test as ts,logsource_cep as cep, logsource_qradaridentifier as qid WHERE ls.id = uc.logsource_id AND ls.id = qid.logsource_id AND qid.id = cep.qid_id")
    #cursor.execute("Select uc.high as category,uc.description as description,ls.type as ltype ,pr.validation as validation, cep.regex as cregex FROM logsource_usecase as uc, logsource_logsource as ls,logsource_parameter as pr, logsource_test as ts,logsource_cep as cep, logsource_qradaridentifier as qid")
    context = {
        'log_list': Detail.objects.all()
    }

    return render(request, 'logsource/logsource_list.html',context)


index = IndexView.as_view()

core/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>{% block title %}RCA{% endblock %}</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<link rel="shortcut icon" type="image/png" href="https://exchange.xforce.ibmcloud.com/images/shortcut-icons/security-shield-social-201x200.png" />
	<link rel="stylesheet" href="{% static 'assets/bootstrap.min.css' %}" media="screen" />
	<link rel="stylesheet" href="{% static 'assets/jquery.dataTables.min.css' %}" media="screen" />
	<link rel="stylesheet" href="{% static 'assets/custom.min.css' %}" media="screen" />
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a href="{% url 'index' %}" class="navbar-brand"><img class="img-responsive" src="{% static 'assets/images/logo.png' %}" alt="RCA" id="logo"></a>
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
          <ul class="nav navbar-nav">
          </ul>
					<ul class="nav navbar-nav navbar-right">
			{% if user.is_authenticated %}
			{% if user.is_superuser %}
			<li><a href="{% url 'admin:index' %}">Admin</a><li>
			{% endif %}
			<li><a href="{% url 'logout' %}">Logout</a></li>
			{% else %}
			<li><a href="{% url 'login' %}">Login</a></li>
			{% endif %}
        </div>
      </div>
    </div>
    <div class="container">
		{% block container %}{% endblock %}
		<footer>
			<div class="row">
			  <div class="col-lg-12">
			    <ul class="list-unstyled">
			      <li class="pull-right"><a href="#top">Top</a></li>
			    </ul>
			  </div>
			</div>
		</footer>
	</div>
	<script src="{% static 'assets/jquery.js' %}"></script>
  <script src="{% static 'assets/bootstrap.min.js' %}"></script>
	<script src="{% static 'assets/jquery.dataTables.min.js' %}"></script>
	<script src="{% static 'assets/main.js' %}"></script>
</body>
</html>

core/templates/contact.html
{% extends "base.html" %}

{% block title %}
    Contact | {{ block.super }}
{% endblock %}

{% block container %}
<div class="page-header">
    <h1>Message</h1>
    <form class="form-horizontal">
        <fieldset>
            <div class="form-group">
              <label for="id_name" class="col-md-3 control-label">Name</label>
              <div class="col-md-9">
                <input type="text" class="form-control" id="id_name" placeholder="Nome" />
              </div>
            </div>
            <div class="form-group">
              <label for="id_email" class="col-md-3 control-label">E-mail</label>
              <div class="col-md-9">
                <input type="text" class="form-control" id="id_email" placeholder="E-mail" />
              </div>
            </div>
            <div class="form-group has-error">
              <label for="id_message" class="col-md-3 control-label">Message</label>
              <div class="col-md-9">
                <textarea class="form-control" rows="3" id="id_message"></textarea>
                <span class="help-block">Message is required</span>
              </div>
            </div>
            <div class="form-group">
              <div class="col-md-9 col-md-offset-3">
                <button type="submit" class="btn btn-primary">Send</button>
              </div>
            </div>
        </fieldset>
    </form>
</div>
{% endblock %}

core/templates/index.html
{% extends "base.html" %}

{% block container %}

<div class="row justify-content-md-center">
  <div style="width:50%;height:100px;"></div>
  <div class="col-sm-8 col-lg-12">
    {% if user.is_authenticated %}
    <div class="jumbotron">
      <h1 class="display-4">Hello, Engineer!</h1>
      <p class="lead">Welcome to RCA</p>
      <hr class="my-4">
      <p>Please click on button to start search.</p>
      <p class="lead">
        <a class="btn btn-primary btn-lg" href="{% url 'logsource:logsource_list' %}" role="button">Begin</a>
      </p>
    </div>
    </div>
    {% else %}
    <div style="width:50%;height:240px;"></div>
    {% endif %}
</div>

{% endblock %}

core/templates/login.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}Sign In | {{ block.super }}{% endblock %}

{% block container %}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="page-header">
            <p></p>
        </div>
        <form class="form-horizontal" method="post">
            {% csrf_token %}
            {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                {{ error }}
            </div>
            {% endfor %}
            <fieldset>
                <div class="form-group{% if form.username.errors %} has-error{% endif %}">
                  <label for="{{ form.username.auto_id }}" class="col-md-3 control-label">{{ form.username.label }}</label>
                  <div class="col-md-9">
                    {% render_field form.username class="form-control" %}
                    {% for error in form.username.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                  </div>
                </div>
                <div class="form-group{% if form.password.errors %} has-error{% endif %}">
                  <label for="{{ form.password.auto_id }}" class="col-md-3 control-label">{{ form.password.label }}</label>
                  <div class="col-md-9">
                    {% render_field form.password class="form-control" %}
                    {% for error in form.password.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                  </div>
                </div>
                <div class="form-group">
                  <div class="col-md-9 col-md-offset-3">
                    <button type="submit" class="btn btn-primary">Send</button>
                  </div>
                </div>
            </fieldset>
        </form>
    </div>
</div>
{% endblock %}

core/templates/logsource.html
{% extends "base.html" %}

{% block title %}
    Losources | {{ block.super }}
{% endblock %}

{% block container %}
<div class="page-header">
  <h1>Losource</h1>
</div>
<div class="row">
  <div class="col-sm-4">
      <a href="#" class="thumbnail">
          <img src="http://placehold.it/350x250" alt="" />
      </a>
  </div>
  <div class="col-sm-8">
      <dl>
        <dt>Lorem ipsum:</dt>
        <dd>Lorem ipsum dolor sit amet</dd>
        <dt>Lorem ipsum:</dt>
        <dd>Lorem ipsum dolor sit amet</dd>
        <dt>Lorem ipsum:</dt>
        <dd>Lorem ipsum dolor sit amet</dd>
        <dt>Lorem ipsum:</dt>
        <dd>Lorem ipsum dolor sit amet</dd>
        <dt>Lorem ipsum:</dt>
        <dd>Lorem ipsum dolor sit amet</dd>
      </dl>
  </div>
</div>
{% endblock %}

core/templates/logsource_list.html
{% extends "base.html" %}

{% block title %}
    Logsource list | {{ block.super }}
{% endblock %}

{% block container %}
<div class="page-header">
    <h1>Logsources</h1>
</div>
<div class="row">
    <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
            <a href="#">
                <img src="http://placehold.it/350x250" alt="" />
            </a>
            <div class="caption">
                <h3>Lorem ipsum dolor sit amet</h3>
                <p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                <p><a href="#" class="btn btn-success" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
            </div>
        </div>
    </div>
    <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
            <a href="#">
                <img src="http://placehold.it/350x250" alt="" />
            </a>
            <div class="caption">
                <h3>Lorem ipsum dolor sit amet</h3>
                <p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                <p><a href="#" class="btn btn-success" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
            </div>
        </div>
    </div>
    <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
            <a href="#">
                <img src="http://placehold.it/350x250" alt="" />
            </a>
            <div class="caption">
                <h3>Lorem ipsum dolor sit amet</h3>
                <p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                <p><a href="#" class="btn btn-success" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
            </div>
        </div>
    </div>
</div>
{% endblock %}